[env]
DEP_GDAL_VERSION_NUMBER="3,080,100"
GDAL_VERSION="3.8.1"
GDAL_STATIC="C:\\Program Files\\GDAL\\lib\\gdal_i.lib"
GDAL_LIB_DIR="C:\\Program Files\\GDAL\\lib"
GDAL_HOME="C:\\Program Files\\GDAL"
GDAL_INCLUDE="C:\\Program Files\\GDAL\\include"
LIBCLANG_PATH="C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\Llvm\\x64\\bin\\libclang.dll"


[alias]
# Run doctests, displaying compiler output.
# Due to this issue:
#    https://github.com/rust-lang/cargo/pull/9705#issuecomment-1226149265
# the following is required for full output during documentation development debugging:
#    RUSTDOCFLAGS="-Z unstable-options --nocapture" cargo +nightly test --doc
dto = "test --doc -- --show-output --nocapture"
# Run clippy, raising warnings to errors
nowarn = "clippy --all-targets -- -D warnings"
